### ISSUE TITLE
Windows 2012: Powershell 5 doesn't work, installing PowerShell 7 still doesn't work

### ISSUE THREAD

**Issue by darkpixel** [lithnet/ad-password-protection#101]
I installed the app on a Windows Server 2012 machine.

The built-in powershell complains it's not new enough which is understandable.

I installed PowerShell 7 and it can't seem to find the Lithnet module:

![Screenshot from 2023-03-15 11-19-55](https://user-images.githubusercontent.com/158380/225407208-38f33704-da9e-436f-bd3a-0ac783457398.png)

**Comment by ryannewington** [comment]
You need to use Windows PowerShell 5.1

https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/setup/install-configure?view=powershell-7.3

"PowerShell" (6+) is not the same as "Windows PowerShell"

https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7.3
