### ISSUE TITLE
Download the latest version of the NTLM (not working)

### ISSUE THREAD

**Issue by worldsdream** [lithnet/ad-password-protection#103]
https://blog.lithnet.io/2019/01/lppad-1.html

Prerequisites (Step 3) is outdated:
Download the latest version of the NTLM passwords from the [haveibeenpwned.com pwned password list](https://haveibeenpwned.com/Passwords) (scroll to the end). Make sure you get the "NTLM Ordered by hash" version. Use the torrent link if you are able to so, as this helps minimize bandwidth and costs. Uncompress the file, and place it on your server to import later in the process.

HIPB changed it to a downloader tool instead.

Can you look into this? Thank you.

**Comment by ryannewington** [comment]
Thanks for highlighting that

Our latest release has a built-in cmdlet for syncing with the hibp api

https://github.com/lithnet/ad-password-protection/releases/tag/v1.1.48

**Comment by worldsdream** [comment]
Looks great.

I will test it next week.

I will run the command "Sync-HashesFromHibp" and it will download the changes, right? 

And if you don't have anything yet configured (fresh configuration), it will start downloading the whole file, right?

Can the documentation be updated when you have time so I can review it?

**Comment by ryannewington** [comment]
Thanks correct. It will populate the store and keep it up to date with subsequent runs

Documentation is at https://docs.lithnet.io/password-protection/v/1.1/
