### ISSUE TITLE
[Enhancement] Minimum number of modified characters

### ISSUE THREAD

**Issue by dw72** [lithnet/ad-password-protection#11]
Because users often change only one sign when change its password, I ask about possibility to set minimum number of modified characters between password changes. It is possible to do this like in showed below commercial solution?

![Sysops screenshot](https://warroom.rsmus.com/wp-content/uploads/2015/02/settings.png)

**Comment by ryannewington** [comment]
Hey @dw72,

I suspect that they must have a client-side module in use here. 

The domain controller never gets the old password as part of the password filter function provided, and of course, the password is stored in the AD database as a one-way hash, making comparisons against that impossible.

Do you know if this feature requires an agent to be deployed to the endpoints themselves for this part to work?

Ryan
