### ISSUE TITLE
I have installed Ad password protection but now every password I try, is not comliant

### ISSUE THREAD

**Issue by ErikPlan** [lithnet/ad-password-protection#111]
I have installed APP, imported just 5 custom words, created GPO, users couldn't change their password.
Then I disabled APP in GP via Disable password filter and it is still blocking changing of password.
I uninstalled APP, and now it works. 
Then I installed again, and as soon as it is installed it blocks users again.
Always with the error:
Unable to update the password. The value provided for the new password does not meet the length complexity or the history requirements.
client: Win 10 
Server: Win 2019

**Comment by ryannewington** [comment]
Hi @ErikPlan 

The LPP event logs will tell you specifically why the password was rejected

https://docs.lithnet.io/password-protection/advanced-help/event-logging-and-reporting

If you don't see any event logs, it's not LPP blocking the password change. Windows policies are enforced first, including the default minimum password age policy that prevents users from changing their password more than once per day. This often is a trip point for LPP testing.

**Comment by ErikPlan** [comment]
Thank you!!!!

It was my mistake, I set up a new AD environment and by default Minimum password age was set to 1 day. Once I changed that to 0, It allowed me to change passwords.
