### ISSUE TITLE
Questions about Lithnet

### ISSUE THREAD

**Issue by alexchurch22** [lithnet/ad-password-protection#12]
I'm currently testing this product in my lab, but have a few questions.

1.	How does Lithnet integrate into Active Directory? I don’t see a service running so I’m assuming it’s attaching to ADDS somehow, but I’d like to understand this before I plan for implementing in production.
2.	I’ve tested on Server 2012 R2 and Server 2019 Core domain controllers and both seem to work. With Server 2019 being relatively new, are there possible issues with Server 2019 and / or Server 2019 Core that the development team is aware of?
3.	We’re planning on implementing our new DCs running Server 2019 Core with Credential Guard. In my tests that doesn’t seem to prevent this tool from working, but are there potential issues with running this tool on a device where Credential Guard is configured?
4.	I don't see a way to remove a hash from the compromised list or a way to remove a banned word from the list of banned words. Is there a way to do this or would this be a feature request?

**Comment by darrenjrobinson** [comment]
1. There are two parts. 
a. The Pwed Password Check using DSInternals Libs that allows online checking. 
b. The Password Filter that allows enforcement of your configuration. Lookup PCNS Password Filters if you want more info on how those work
2. I've got it working with Server 2019. In order for full functions you will need Read/Write Domain Controllers. These functions will work moving forward as it would be a breaking change to move away from these functions.
3. None known.
4.  I can't see that either. @ryannewington ??

**Comment by alexchurch22** [comment]
Thank you very much for your answers. I'll do some reading about PCNS Password Filters. We're in the middle of planning for an O365 migration. If a user changes their password in Office 365 to a value that Lithnet would reject, would it be accepted? We haven't set up password writeback yet, but it looks like ([from this document](https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-sspr-writeback)) that it requires the "change password" permissions so I would hope that the change would be rejected and the user would receive a message about it not meeting complexity requirements.

**Comment by darrenjrobinson** [comment]
If you have your AAD Federated with AD and have Password Write-Back enabled then password changes in AAD/O365 will respect the OnPrem AD Password Policies.

**Comment by ryannewington** [comment]
I'm working on Remove-BannedWord now!

**Comment by ryannewington** [comment]
Removed-BannedWord and Remove-CompromisedPassword now available in this release https://github.com/lithnet/ad-password-protection/releases/tag/v1.0.7107

**Comment by ryannewington** [comment]
@alexchurch22 is there any other assistance you need on this topic?

**Comment by alexchurch22** [comment]
@ryannewington no, thank you very much!
