### ISSUE TITLE
Part of display name in password IS accepted

### ISSUE THREAD

**Issue by hapitou** [lithnet/ad-password-protection#120]
Hi team

we have problems with lithnet which accepts passwords containing part of the characters of the displayname
Version 1.48 or last bug is présents

Thanks
Hapion

**Comment by ryannewington** [comment]
@hapitou 

Can you provide an example of a display name and password that is being accepted?

**Comment by hapitou** [comment]
As you see below, the password part ("Pier") of DisplayName "Pierre" in password

![image](https://github.com/lithnet/ad-password-protection/assets/82226873/94015677-c1d0-451f-8a23-97ca9e946fe4)
![image](https://github.com/lithnet/ad-password-protection/assets/82226873/4ce2273f-dc77-4e2d-bd2d-29c734e6b404)
Password contains full display name is rejected 
![image](https://github.com/lithnet/ad-password-protection/assets/82226873/b76ae745-1cb6-4923-9505-9e470ff88487)

**Comment by ryannewington** [comment]
@hapitou The filter splits on spaces in the full name, and looks for full matches. So 'pierre' or 'richard' would be blocked, but substrings of those words will not be matched.

**Comment by hapitou** [comment]
Thanks Ryan, because documentation was mentioned part of display name and i have checked the code (fonction below Line 200 of passwordevaluator.cpp)  that seems effectively :BOOLEAN ProcessPasswordDoesntContainFullName(const SecureArrayT<WCHAR> &password, const std::wstring &accountName, const std::wstring &fullName, const BOOLEAN &setOperation, const registry &reg){..
Thx
    Le dimanche 28 janvier 2024 à 09:19:21 UTC+1, Ryan Newington ***@***.***> a écrit :  
 
 


@hapitou The filter splits on spaces in the full name, and looks for full matches. So 'pierre' or 'richard' would be blocked, but substrings of those words will not be matched.
