### ISSUE TITLE
lithnetpwdf.dll not loaded

### ISSUE THREAD

**Issue by hapitou** [lithnet/ad-password-protection#121]
Hi ,

We have issue with lithnet which doesn't on a domain controler W2K12 R2, all is installed (.net 4.8, vcx64), but impossible to use lithnet :
![image](https://github.com/lithnet/ad-password-protection/assets/82226873/f210d7bd-7255-4d33-9bf4-29a3e92d6c5f)
Can you help me please ?

Thx

**Comment by ryannewington** [comment]
A few things to check:

Are you running the x64 version of PowerShell? 

Are there any notable events in the event log that indicate why there is an issue loading the module?

Any EDR/Antivirus systems that would be preventing it from loading?

Do you get an event in the Windows Event Log when the computer started saying that the Lithnet Password Protection filter was loaded?

**Comment by hapitou** [comment]
Hi ,
Thanks for you reply.The issue was resolved.Indeed, the system needs to be update to last patchs , i dont know what IS patch exactly but it IS recommended to patch with last in order the dll loads
Thx
    Le dimanche 28 janvier 2024 à 09:23:52 UTC+1, Ryan Newington ***@***.***> a écrit :  
 
 


A few things to check:

Are you running the x64 version of PowerShell?

Are there any notable events in the event log that indicate why there is an issue loading the module?

Any EDR/Antivirus systems that would be preventing it from loading?

Do you get an event in the Windows Event Log when the computer started saying that the Lithnet Password Protection filter was loaded?
