### ISSUE TITLE
Restricting usage of Turkish Characters in AD Passwords

### ISSUE THREAD

**Issue by m4573rbl4573r** [lithnet/ad-password-protection#124]
Hi everyone,

As a new user, i've installed and by reading the documentation configured 'Lithnet Password Protection'. My main purpose was to restrict the use of turkish characters (şŞçÇİığĞüÜöÖ) as our VPN solution and Exchange OWA doesn't support them.

After the installation i have created a new policy and linked it to domain controllers OU, however there are some things i couldn't make sure of;

Should i also link the policy object to client computers OU?
I couldn't managed to get this work using 'passwords must not match a specified regular expression' setting with /[şŞçÇİığĞüÜöÖ]/ given as regex value.

Any information on these would really helpful to me, thank you.

**Comment by ryannewington** [comment]
The policy only needs to link to the domain controller OUs.

I think your expression isn't correct. It should be something like this (and no leading or trailing `/`)
`[şŞçÇİığĞüÜöÖ]+`
