### ISSUE TITLE
Complexity policies and number of character sets

### ISSUE THREAD

**Issue by ubrbs2** [lithnet/ad-password-protection#125]
Hi there
In the complexity policies it is possible to require a number of character sets to be present.
But you can only require the use of at least **one** number or **one** symbol and so on. You can not require the use of at least two or more numbers or two or more symbols and so on.
We would like to have a complexity policy that requires at least two numbers and two symbols and two uppercase letters and two lowercase letters.
Is there any way to achieve this ?

**Comment by ryannewington** [comment]
@ubrbs2 You could potentially do this with a regular expression, but there isn't anything in the complexity rule engine itself to accommodate this.
