### ISSUE TITLE
Edit group policies any programmatic way

### ISSUE THREAD

**Issue by MakaronniyMonstr** [lithnet/ad-password-protection#128]
Does any programmatic way exists to change lithnet password policies?
Powershell, c#, any way.

**Comment by ryannewington** [comment]
Hi @MakaronniyMonstr 

The policies are set in the registry of each domain controller, usually via group policy.

If you don't want to set them by group policy, you can set them directly in the registry. A very raw list of the key names and locations are here.

You'd store them under `HKLM\SOFTWARE\Lithnet\PasswordFilter\default`

https://github.com/lithnet/ad-password-protection/blob/master/src/PasswordFilter/registry.h

**Comment by MakaronniyMonstr** [comment]
Thx. This works, but pay attention that you use “Global Policy Editor” instead of “Local policy editor”.
