### ISSUE TITLE
Get List of currently banned words

### ISSUE THREAD

**Issue by Tranquillo1811** [lithnet/ad-password-protection#131]
is this possible?

best regards
Olli

**Comment by ryannewington** [comment]
Hey Olli,

The banned words are hashed with a one-way hash, so you can test for them with `Test-IsBannedWord` but there currently isnt a function to retrieve the list.

We generally recommend keep a plain-text list of the banned words you want to keep track of, and you can always import that list after making changes. LPP will ignore any duplicates already in the list on import.
