### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by Gattsun** [lithnet/ad-password-protection#132]
Hello,

I read that you can supposedly use wildcards with this but after investigating further and trying a few things like adding the banned words using stuff like "*Amazon *" or "*amazon" etc. It still lets the passwords through? Ive tried adding it to both banned and compromised lists but seemingly not working. Can anyone tell me what I am doing wrong or is it actually not possible?

https://docs.lithnet.io/password-protection/advanced-help/powershell-reference/test-isaduserpasswordcompromised

This section also seems to suggest that it can read some sort of wildcards

**Comment by ryannewington** [comment]
@Gattsun 

You can't add wildcards as such, but you don't need to.

If you want to block verbatim use of passwords. Import it as a compromised password. This will prevent use of that specific password.

If you want to prevent passwords based on simple words with common substitutions, then import it as banned word. So if you imported "Amazon" it would prevent simple passwords based on the word Amazon. However it doesn't prevent the use of the word Amazon in a safe way.
This means passwords like Amazon123! or am4z0n are blocked. But passwords that use Amazon in a difficult to brute force way like "the Amazon is my favorite forest" are allowed.

More on normalisation rules here https://docs.lithnet.io/password-protection/advanced-help/normalization-rules

Also the test-isadpasswordcompromised cmdlet can only check compromised passwords, not banned words. The passwords in AD are stored as a one-way hash, so we can only compare exact matches, unlike at password change time where we can inspect the plain text password.

**Comment by Gattsun** [comment]
I see, thank you for the information.

The idea is that my company doesn't want the company's name anywhere in the password along with some other company associated words. I tried adding the words and then making a password that matched the current password requirements like 1 symbol, 1 number,  uppercase letter and capital letter and it being 12 characters long at the minimum. I assume those requirements don't make it into a "difficult to brute force way" password? Cause when I did try passwords like that, it seemed like the filter was letting them through but perhaps I was doing something wrong as well.

I'll try the banned words again tomorrow then.

**Comment by Gattsun** [comment]
Hello,

I still seem to struggle with it. Perhaps I am not understanding this correctly.

So I have a txt file with passwords like this on seperate lines.

dell
lenovo
logitech
microsoft
windows

I used Import-BannedWords -Filename to import in the txt file. I did it for both banned and compromised just in case or does that interfere with eachother? I did this on all my domain controlers

So then I made a gpo with these settings

![image](https://github.com/user-attachments/assets/e6c67b5b-0577-4497-a6fa-67a846b4144e)

All domain controllers  have been gpupdated and then I try a password like "Microsoftrocks2005#!" and it lets it through? I don't get it. Does that fall under the brute force way password?

**Comment by ryannewington** [comment]
It's not going to block the use of multiple words like Microsoftrocks2005!. That password would get 'normalized' down to `microsoftrocks` which isn't in your banned word list.

It stops passwords based on a _single_ word, with common substitutions. It will always allow use of words in ways that are not present in common brute forcing dictionaries.

If you want to block _any_ usage of say your company name, use a regular expression rule instead.
