### ISSUE TITLE
invalid access to memory location when creating a new AD user account

### ISSUE THREAD

**Issue by RyanLKN** [lithnet/ad-password-protection#133]
Has anyone experienced a memory location issue when attempting to create a user account after installing LithnetPasswordProtection-1.1.55 on a Windows Server 2016 machine?
<img width="293" alt="image" src="https://github.com/user-attachments/assets/fb54b2f9-c368-4eca-a3a8-5e1e77e140d5">

**Comment by ryannewington** [comment]
If you disable the password filter via GPO, does this error go away?

**Comment by RyanLKN** [comment]
Disabling the GPO is no help, but everything returns to normal after removing Lithnet. I have tested this on 6 Windows 2016 servers, and they all exhibit the same symptom.

**Comment by Darklance-nl** [comment]
I also have this issue
@ryannewington 
Uninstalled the lithnet software

**Comment by darknanox** [comment]
Same. Tried also on a new test domain controller 2022, same error when you try to set a password.

**Comment by RyanLKN** [comment]
@Darklance-nl I thought it was a GPO issue too, but the issue happened both before and after enabling GPO.

**Comment by ryannewington** [comment]
Thanks for the info. We're investigating this issue now.

**Comment by arth0sz** [comment]
Can confirm the same issue on Server 2019 as well when trying to reset a user's password, installed it in a lab environment for testing.

**Comment by ryannewington** [comment]
Hi all, we can reproduce the issue and are working on a fix. In the mean time, please use v1.1.53

**Comment by ryannewington** [comment]
Hi all, can you try installing the latest version of the C++ runtime and see if that solves the issue for you

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

**Comment by arth0sz** [comment]
I can confirm that in my case installing the latest C++ runtime did fix the issue, had to restart after the installation though.

**Comment by ryannewington** [comment]
Thanks for confirming. Our tests are showing the same. We're updating the LPP installer to install the latest version of the C++ runtime to resolve this. It should be released tomorrow.

**Comment by ryannewington** [comment]
Thanks for confirming. Our tests are showing the same. We're updating the LPP installer to install the latest version of the C++ runtime to resolve this. It should be released tomorrow.

**Comment by ryannewington** [comment]
Hi all, [1.5.57 has been released](https://docs.lithnet.io/password-protection/setup/downloads) which includes the updated version of the VC runtime which addresses this issue.

Note you can just upgrade the VC runtime to the latest and stay on 1.5.55. There were no code changes to LPP itself.
