### ISSUE TITLE
Nothing in the event viewer?

### ISSUE THREAD

**Issue by nebulight** [lithnet/ad-password-protection#134]
We just spun up a brand new test domain. Nothing else is installed on this server other than lithnet. I'm not getting anything in the event viewer. I did search and couldn't find any events about errors loading the password filter. I was looking at other posts and tried to register the DLL and got this:

![{716626EC-786B-4FC4-8AEF-19A73FF6ED97}](https://github.com/user-attachments/assets/837d9f48-b8f6-4d4a-a953-62bd7812b69e)

Server is 2022. Odd thing is we have this installed on production DCs that are also 2022 and it's working fine. Some other reg queries:

![{08C5A1E1-442F-4F41-A77E-E752C18963DF}](https://github.com/user-attachments/assets/df018454-2c66-4c95-b6af-80bf6164d171)

Trying to get this up and running for some more testing with Lithnet before we deploy to production. Not sure what is different with this installed. Attempted to reinstall with no change.

Thanks.

**Comment by ryannewington** [comment]
Hi @nebulight 

The regsrv32 doesn't work with this type of DLL. However, it is correctly registered as a notification package as we can see in the screen shot.

There's another issue we are investigating at the moment, just to rule this out, can you try updating the Visual C runtime to the latest version and reboot?

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

We're looking for a single event at startup to say that LPP was loaded.

**Comment by nebulight** [comment]
> Hi @nebulight
> 
> The regsrv32 doesn't work with this type of DLL. However, it is correctly registered as a notification package as we can see in the screen shot.
> 
> There's another issue we are investigating at the moment, just to rule this out, can you try updating the Visual C runtime to the latest version and reboot?
> 
> https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version
> 
> We're looking for a single event at startup to say that LPP was loaded.

Thanks for the quick reply. This worked for getting event ID 3 showing that the filter has been successfully loaded. However I get nothing after that. I set my default domain policy only a max of 7 characters and turned off everything else. It doesn't allow me to use a compromised password, but it's just not logging on the DC. We are attempting to setup rules in our SIEM when users attempt, but can't get that working without logged events :(

Any other suggestions?

**Comment by ryannewington** [comment]
Try using PowerShell to test your filter in a more managed way 

https://docs.lithnet.io/password-protection/setup/testing-the-password-filter#testing-the-password-filter-using-powershell

And check the policy that is in place

https://docs.lithnet.io/password-protection/advanced-help/powershell-reference/get-passwordfilterpolicy

and the overall filter status

https://docs.lithnet.io/password-protection/advanced-help/powershell-reference/get-passwordfilterconfig

**Comment by nebulight** [comment]
![image](https://github.com/user-attachments/assets/af77c42e-9c85-48fe-acc7-3a3e92df11af)

It was working and this logged my attempt in the event viewer:

![image](https://github.com/user-attachments/assets/62653913-141a-40a9-9bc1-84a82e378973)

Did I miss a step? Do I need to apply the GPO to the workstations as well? I thought it was just for the DCs?

**Comment by ryannewington** [comment]
Ok that's good - that tells us that the filter is working and is correctly configured.

If it's not appearing in the event log from performing a 'real' password change, that's mostly likely because windows is rejecting it before it gets to the LPP filter. If windows policy stops the password from being changed, it will never get to LPP for evaluation, and you'll never see an event entry.

Most common cause is minimum password age. If you have this set, users cannot change their password more than once per day - a common pitfall when trying to test.

**Comment by nebulight** [comment]
Hmmm, not sure what the workstation would be doing as it appears to have gotten my stripped pw policy:

![{BF9A86D7-63E9-4B53-9098-2F3DB5BB3C24}](https://github.com/user-attachments/assets/fe438b37-445d-4ff6-84ca-2b7293b1a946)

I'll try it again next week.

**Comment by ryannewington** [comment]
It's the password policy on the DC that applies, not the local workstation.

**Comment by nebulight** [comment]
Thank you. You are correct, I thought changing the policy on the default domain policy would do it, but looks like the user is still showing as password not changeable. If you want to close this issue, that's fine. Or keep it open for the latest runtime?

Thanks again!

![{BF9A86D7-63E9-4B53-9098-2F3DB5BB3C24}](https://github.com/user-attachments/assets/b2a62d00-3cab-4737-a44d-e424eb7729f2)

Thanks again!!
