### ISSUE TITLE
Get-PasswordFilterResult Failing

### ISSUE THREAD

**Issue by AaronGenter** [lithnet/ad-password-protection#14]
We're just setting up this solution. After the initial setup, trying to run Get-PasswordFilterResult fails with the following:

Get-PasswordFilterResult : Unable to load DLL 'lithnetpwdf.dll': The specified module could not be found. (Exception
from HRESULT: 0x8007007E)
At line:1 char:1
+ Get-PasswordFilterResult -Password P@ssw0rd123 -Username *** -Ful ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PasswordFilterResult], DllNotFoundException
    + FullyQualifiedErrorId : System.DllNotFoundException,Lithnet.ActiveDirectory.PasswordProtection.PowerShell.GetPas
   swordFilterResult

I can successfully run Test‐IsCompromisedPassword to get that the password is included in the list.

Thanks!

**Comment by ryannewington** [comment]
@AaronGenter, apologies for this issue. There was a problem with the last build.

This has been resolved in the following release.

https://github.com/lithnet/ad-password-protection/releases/tag/v1.0.7123

Let me know how it goes

**Comment by AaronGenter** [comment]
Thank you for the quick response! The Powershell command now works properly and I was prevented from setting a compromised password.
