### ISSUE TITLE
Support running LPP in LSA protected mode

### ISSUE THREAD

**Issue by AaronG1234** [lithnet/ad-password-protection#15]
https://docs.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection
(emphasis mine)

Signature verification

Protected mode requires that any plug-in that is loaded into the LSA is digitally signed with a Microsoft signature. Therefore, any plug-ins that are unsigned or are not signed with a Microsoft signature will fail to load in LSA. Examples of these plug-ins are smart card drivers, cryptographic plug-ins, and ___password filters___.

anyway you could get your DLL signed so that it would be usable with LSA Protected "Mode"

**Comment by ryannewington** [comment]
Hi @AaronG1234,

I've been wanting to do this for a while, but unfortunately an EV code signing certificate is required for this, and they are not cheap. I'll take another look around and see if I can find one affordable, or a CA that offers cheaper rates for open source projects.

Ryan

**Comment by AaronG1234** [comment]
digicert has a hidden special, accessable from

https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate#step-2-buy-a-new-code-signing-certificate

https://www.digicert.com/friends/sysdev/
(click Ok button)

104USD per year for EV
________________________________

**Comment by ryannewington** [comment]
Yeah I found that and just got in contact with them for going through the process to validate Lithnet. I use them for the current code-signing certificate, so hopefully it's a straight forward process to upgrade lithnet's org verification level to the level required for EV. EV certs require a hardware token though, so provided all goes well, they need to ship that out and will take a few weeks.

**Comment by ryannewington** [comment]
It looks like we should be able to make this happen. We've set up a page to gather donations to help cover the cost of the EV (https://lithnet.io/donate). I'll keep you posted on the progress.

**Comment by AaronG1234** [comment]
Thanks so much for considering this... I wrote my own lsa notification filter about a year ago that uses pwnedpasswords api.  but when we moved to lsa protected, it wouldn't load.

(btw i put in a feature request for allowing api.pwnedpasswords.com as an alternative to downloading the hashes)
________________________________

**Comment by ryannewington** [comment]
@AaronG1234 we were able to raise the money, thanks to some generous donations, including yours. Thankyou for your contribution.

re: the feature request, that's a good idea, i can look to add that in. Do you mind raising a new issue for it?

**Comment by AaronG1234** [comment]
i did already.  (also i have code for it, however it is really fundamental idea and as I look at your source code I dont think you need much 'splaining...and I am not a C programmer by heart ... because I hate how convoluted strings are in C... ... but dont tell anyone)
________________________________

**Comment by ryannewington** [comment]
Maybe it didn't save? Have created a new one for you to follow for updates. 

https://github.com/lithnet/ad-password-protection/issues/18#issuecomment-513535147

Code is linked in the comment if you want to have a look over. If there are any gotchas you learnt from your own implementation I should be aware of, do let me know. 

We'll keep this thread on the LSA protection support feature now.

**Comment by ryannewington** [comment]
First build with the MS-signed binary is up!

https://github.com/lithnet/ad-password-protection/releases/tag/v1.0.7143
