### ISSUE TITLE
 The file contained a line that was not recognized as a hexadecimal hash

### ISSUE THREAD

**Issue by atrisk99** [lithnet/ad-password-protection#17]
Having the same issue as bodysoda was having before, when i run the Import-CompromisedPasswordHashes it immediately returns the hexadecimal hash error. I originally tried this on my domain controller and have also tried on my pc with same results. 
I downloaded the recommended version and upzipped with z7. 

The file size is:
18.6 GB (20,031,419,880 bytes)

Have checked the SHA-1 hash of the z7 file and matches. 

The hash of the .txt is:
de650566cbd3fefe307105e9615ed3aca3c6c96b

The type command pulls this:
00000001F4A473ED6959F04464F91BB5:4
0000000F23B59311F4FFB01D6D620487:2
000000113BDEB707C98A8234826BF788:4
000000128830292D92FA6B226EEC986B:3
00000015B1284879951DC072C80735DC:3
0000001991F12B30E3B00E7CCED2ADFB:1
0000001FE8FBE6BE79FC5A0D39CDFD68:4
0000002ACC41B93A9CFB5E227503E6F2:3
000000307E7F80DC6BB8572C0DA9A8BA:3
000000393819A00A1DD98DCCA628B8F7:2

everything as i can tell checks out. maybe i should re-download but if the hash is right you wouldn't think so.

**Comment by ryannewington** [comment]
Weird. Are you able to recompress the file and host it somewhere for me to download? I don't want the zip file you downloaded, rather whatever was extracted that is not working.

**Comment by atrisk99** [comment]
Will do so today

**Comment by ryannewington** [comment]
@atrisk99 I was able to reproduce this. There may be a problem with the v5 pwned password source which I am looking into.

This build has some improved error messages when there is an import problem. Are you able to execute the cmdlet using this build and report back on the error message.

https://github.com/lithnet/ad-password-protection/releases/tag/v1.0.7143

**Comment by atrisk99** [comment]
Import-CompromisedPasswordHashes : Line #2345 was not recognized as a hexadecimal hash. The line was not the expected
length.
The following line was invalid:
NULL
At line:1 char:1
+ Import-CompromisedPasswordHashes -Filename C:\temp\pwned-passwords-nt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-CompromisedPasswordHashes], InvalidDataException
    + FullyQualifiedErrorId : System.IO.InvalidDataException,Lithnet.ActiveDirectory.PasswordProtection.PowerShell.Imp
   ortCompromisedPasswordHashes

**Comment by ryannewington** [comment]
This has been confirmed as a problem with the source data. I will let you know when the corrected dataset is available for download.

**Comment by atrisk99** [comment]
Thanks!!!

**Comment by ryannewington** [comment]
@atrisk99 Troy has fixed the source file, so you can redownload it from his web site and all should be fine now.
