### ISSUE TITLE
Question about normalization

### ISSUE THREAD

**Issue by alexchurch22** [lithnet/ad-password-protection#19]
I've read the wiki page on [normalization](https://github.com/lithnet/ad-password-protection/wiki/Normalization-rules), but I have some questions. I'd like to understand what criteria it's using when the normalization is used 

In the example "Winter2018" boils down to "winter" after the normalization rules are applied. When the password filter is set to use normalization against the compromised password list, is it then just looking for the hash of the password "winter" exactly in the database of compromised hashes? Or is it performing some normalization of the passwords in the databases as well?

**Comment by ryannewington** [comment]
Hi Alex,

Let's look at the two policy options that come into play with normalized words and unpack each process.

1. Reject normalized passwords found in the compromised password store
2. Reject normalized passwords found in the banned word store

Both policies start with the same normalization process. Eg A user tries to change their password, we see the plain-text version of that password and normalize it. So our _input_ value of 'Winter2018' is converted to 'winter'. The value is then hashed before being compared to a value in the stores.

An important note is that the *compromised password store* and *banned word store* both contain only hashes, so we can only ever do a hash-based comparison.

So if the there was a password in the *compromised password store* that exactly matched "winter" then it would be rejected. If the compromised password in the store was "winter1", that wouldn't match. The normalization is done on the _input_ password, not the value saved in the store.

However, this is where *banned words* behave a little differently. While it is still true that these values are stored as hashes, when you add values to the banned word store, they are normalized _before_ being hashed and _saved_ to the *banned word store*. So if you tried to add "winter1" to the banned word store, it would be normalized to "winter" before being saved. This means that using policy (2), a user could provide "Winter2018" as the password, it would be normalized to "winter" and therefore match the value in banned word store.

Let me know if I've clarified the situation for you.

Ryan

**Comment by alexchurch22** [comment]
That clears things up, thank you!
