### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by zjorz** [lithnet/ad-password-protection#22]
"Enable length-based complexity rules"
Thresholds:
Threshold 1 - less than X
Threshold 2 - longer than X and less than Y
Threshold 3 - longer than Y

What happens when the password equals X or Y?

**Comment by zjorz** [comment]
Total number of character sets required (number, symbol, lower case letter, upper case letter) - Clear!
Exact characters sets required:
Lower case letter
Upper case letter
Symbol
Number
Number or symbol
What is the definition of EXACT?
[1] It must have only any checked character set and not any other unchecked character set?
OR
[2] It must have at least any checked character set

It looks like [2] is the correct answer. Correct?

**Comment by ryannewington** [comment]
Threshold 2 - longer than or equal to X and less than Y

**Comment by ryannewington** [comment]
Where are you seeing the wording from your second comment?

**Comment by zjorz** [comment]
> Threshold 2 - longer than or equal to X and less than Y

if the password length is X. Does threshold 1 or 2 apply?
if the password length is Y. Does threshold 2 or 3 apply?

In both cases it mentions "longer than" and "less than", so when it is exact the specified length according to text in GPO it does not fall in any threshold
Shouldn't the text say either "equal to or longer than" and "less than" OR "longer than" and "equal to or less than"? I would prefer the "longer than" and "equal to or less than"

**Comment by zjorz** [comment]
> Where are you seeing the wording from your second comment?

"Exact characters sets required" is mentioned in the GPO. If it is option [2] I would suggest to change the text to "At least the following checked character sets" (or something similar)
https://github.com/lithnet/ad-password-protection/wiki/Configuring-a-length-based-complexity-policy DOES NOT mention "exact"

**Comment by ryannewington** [comment]
https://github.com/lithnet/ad-password-protection/blob/f5ad388b85f094aa8a75a87b2b3331aec2c5f4d3/src/PasswordFilter/complexityevaluator.cpp#L52

The second threshold should read equal to or longer than the first threshold value.

**Comment by ryannewington** [comment]
It means that all those character sets must be present. 

So you can either say I want at least X number of character sets to be present. Eg I don't care what characters are used as long as there is diversity in the password. (Must contain 3 out of 4 of upper, lower, symbol or number)

Or

You are saying the user MUST have ALL the selected character sets in their password.

**Comment by zjorz** [comment]
> https://github.com/lithnet/ad-password-protection/blob/f5ad388b85f094aa8a75a87b2b3331aec2c5f4d3/src/PasswordFilter/complexityevaluator.cpp#L52
> 
> The second threshold should read equal to or longer than the first threshold value.

thanks, that clears it up!

**Comment by ryannewington** [comment]
No probs. Will fix the doco for the next release

**Comment by zjorz** [comment]
> It means that all those character sets must be present.
> 
> So you can either say I want at least X number of character sets to be present. Eg I don't care what characters are used as long as there is diversity in the password. (Must contain 3 out of 4 of upper, lower, symbol or number)
> 
> Or
> 
> You are saying the user MUST have ALL the selected character sets in their password.

Total number of character sets required (number, symbol, lower case letter, upper case letter) - Clear!
Exact characters sets required:
Lower case letter
Upper case letter
Symbol
Number
Number or symbol
What is the definition of "EXACT"? (as written in the GPO setting)
[1] It must have only any checked character set and not any other unchecked character set?
OR
[2] It must have at least any checked character set

example:
[X] Lower case letter
[X] Upper case letter
[ ] Symbol
[ ] Number
[ ] Number or symbol

when I configure the above I want AT LEAST a lower case and upper case and I do not care if IN ADDITION the user would also use a symbol and/or a number and "number or symbol"

Therefore I think we are both saying "[2] It must have AT LEAST any checked character set" (the word EXACT may be confusing and personally I think AT LEAST fits better)

**Comment by zjorz** [comment]
char subsitution:

can the following be added?
6 --> b (g?)
3 --> e or m or w
9 --> g or q
! --> i or l
1 --> i or l
7 --> j or t
5 --> s
+ --> t

is it even possible to have multiple replacement options like for example the "3". I can imagine that can turn into a nightmare as you would end up with multiple (if not many due to exponential increase) passwords to check against the store

**Comment by zjorz** [comment]
is it possible to VIEW all the words in the Banned Words list?

is it possible to CLEAR all the words from the Banned Words list and the passwords from the Compromised Passwords list?

**Comment by ryannewington** [comment]
> is it possible to VIEW all the words in the Banned Words list?
No they are sha1 hashed before being added to the store 

> is it possible to CLEAR all the words from the Banned Words list and the passwords from the Compromised Passwords list?
in the store folder, delete the contents of the 'w' folder to clear the banned word store, and the 'p' folder to clear the compromised password store

**Comment by zjorz** [comment]
> > is it possible to VIEW all the words in the Banned Words list?
> 
> No they are sha1 hashed before being added to the store
> 
> > is it possible to CLEAR all the words from the Banned Words list and the passwords from the Compromised Passwords list?
> 
> in the store folder, delete the contents of the 'w' folder to clear the banned word store, and the 'p' folder to clear the compromised password store

thanks!

**Comment by zjorz** [comment]
do you have any restrictions regarding the length of a banned word? For example MSFT has a restriction that a word must at least be 4 chars and a max of 16 chars and has a limit of 1000 words.

**Comment by zjorz** [comment]
suggestion....
you have Test-IsBannedWord which normalizes and it gives an unexpected result, IMHO

for example:
"activedirectory" is in the Banned Words list

[1] Test-IsBannedWord "activedirectory" returns TRUE (expected)
[2] Test-IsBannedWord "activedirect0ry" returns TRUE (expected)
[3] Test-IsBannedWord "@ctivedirectory" returns FALSE (not expected)

with the last one it took some time to understand and I think the issue is due to the normalization rules where numbers and symbols at the beginning and end are stripped

Suggestion:
Test-IsBannedWord --> no normalization and just to test is a word in its form is in the banned word list
Test-IsBannedPassword --> supporting the actual password and the password after normalization rules

still does not solve the issue that I would be able to use @ctivedirectory as a password. The only thing I can think of is to test both the actual password and the stripped version after using normalization rules. Would require additional processing

**Comment by zjorz** [comment]
Do you envision in enhancing the following 2?:
"Points-based complexity policy definition" --> assigning points to number of banned words used in password (basically like the MSFT algorithm)

"Regular expression policies" --> for example I would like to be able to create a regular expressions similar to ^$BANNED([0-9]|[a-z]|[A-Z]){1,8}$ and define that in the "passwords must not match a specified regular expression" where $BANNED is one of the banned words from the banned words list

**Comment by zjorz** [comment]
I must be missing something....

On my TEST DCs:
Get-PasswordFilterResult -Password 'Pa$$w0rd' -Username "john.doe" -Fullname "John Doe"
Compromised

On my workstation (pointing to the same store as the DCs, but using UNC path)
Get-PasswordFilterResult -Password 'Pa$$w0rd' -Username "john.doe" -Fullname "John Doe"
Approved

What am I missing here?

**Comment by ryannewington** [comment]
> do you have any restrictions regarding the length of a banned word? For example MSFT has a restriction that a word must at least be 4 chars and a max of 16 chars and has a limit of 1000 words.

No limits. Unlimited banned words of unlimited length.

**Comment by ryannewington** [comment]
I'm going to move some of these into their own issues, because i'm going to loose track of them

**Comment by ryannewington** [comment]
> I must be missing something....
> 
> On my TEST DCs:
> Get-PasswordFilterResult -Password 'Pa$$w0rd' -Username "john.doe" -Fullname "John Doe"
> Compromised
> 
> On my workstation (pointing to the same store as the DCs, but using UNC path)
> (and.... the GPO is applied to the workstation and has the filter and posh module installed!)
> Get-PasswordFilterResult -Password 'Pa$$w0rd' -Username "john.doe" -Fullname "John Doe"
> Approved
> 
> What am I missing here?

Either the GPO isn't applying, or the store path is not correct. When you installed the module it may have defaulted to putting the store path in your profile files folder on the local machine. You can override this with the `Open-Store` cmdlet

**Comment by zjorz** [comment]
> > I must be missing something....
> > On my TEST DCs:
> > Get-PasswordFilterResult -Password 'Pa$$w0rd' -Username "john.doe" -Fullname "John Doe"
> > Compromised
> > On my workstation (pointing to the same store as the DCs, but using UNC path)
> > (and.... the GPO is applied to the workstation and has the filter and posh module installed!)
> > Get-PasswordFilterResult -Password 'Pa$$w0rd' -Username "john.doe" -Fullname "John Doe"
> > Approved
> > What am I missing here?
> 
> Either the GPO isn't applying, or the store path is not correct. When you installed the module it may have defaulted to putting the store path in your profile files folder on the local machine. You can override this with the `Open-Store` cmdlet

Hey Ryan, the GPO was applied and store path was also correct as all other commands were working OK (e.g. Test-IsBannedWord). Tried this morning again and it now does give me the same result. Weird!
