### ISSUE TITLE
Banned and compromised passwords getting approved

### ISSUE THREAD

**Issue by ctdhr** [lithnet/ad-password-protection#27]
Hello,
I'm looking to implement LPP on my organisation's Active Directory DCs, and I've started doing some testing to understand how it works, and how to configure it correctly.

## My testing environment
- Windows 10 Professional 1803 with all the latest updates
- Powershell 5.1.17134.858
- Standalone workstation (not connected to any domains/AD)
- LPP executable v1.0.7143 (full install)

## GPOs

Here's an overview of the group policy objects.

![image](https://user-images.githubusercontent.com/12020172/64171002-d0aa3800-ce51-11e9-98ab-d23703c7c499.png)

Sorry, it's in french. "Activé" means "activated", "Non configuré" means "not configured".

## The issue

I've used the Powershell Module to do the basic testing.

```
PS C:\Users\ctdhr> Import-Module LithnetPasswordProtection

PS C:\Users\ctdhr> Open-Store -Path 'C:\Users\ctdhr\Documents\store'

PS C:\Users\ctdhr> Add-BannedWord -Value "testword"

PS C:\Users\ctdhr> Test-IsBannedWord "testword"
True

PS C:\Users\ctdhr> Get-PasswordFilterResult -Password "testword123" -Username "Myusername" -Fullname "Myusername Infull"
Approved

PS C:\Users\ctdhr> Get-PasswordFilterResult -Password "Myusername_is_great" -Username "Myusername" -Fullname "Myusername Infull"
ContainsAccountName

PS C:\Users\ctdhr> Get-PasswordFilterResult -Password "Infull" -Username "Myusername" -Fullname "Myusername Infull"
ContainsFullName

PS C:\Users\ctdhr> Add-CompromisedPassword -Value "testword123"

PS C:\Users\ctdhr> Get-PasswordFilterResult -Password "testword123" -Username "Myusername" -Fullname "Myusername Infull"
Approved
```

## Expected behaviour

`BannedNormalizedWord` and `Compromised` instead of `Approved`.

I've read the wiki and the getting started blog posts, and have not found any obvious configuration errors. So what am I missing ?

Thanks for you help

**Comment by ryannewington** [comment]
@ctdhr,

Thanks for the comprehensive isue report.

I suspect what is happening is that the LPP agent is actually pointing to the default store location that was set up at installation time. 

The `Open-Store` cmdlet allows you to connect to a store to modify it with the `Add-*` cmdlets. However, `Get-PasswordFilterResult` does not use the store specified by `Open-Store`. It interrogates the password filter installed on the machine, that the password filter uses its own group policy and store configuration.

You can update the path of the store that the filter uses by editing the registry key `HKLM\Software\Lithnet\PasswordFilter\Store`

Let me know if that solves your issue

Ryan

**Comment by ctdhr** [comment]
Thanks for your swift reply @ryannewington 
Right on the money. That was the problem, and it's now solved. 

I had not thoroughly read the [Open-Store cmdlet documentation](https://github.com/lithnet/ad-password-protection/wiki/Open%E2%80%90Store) and just assumed that calling it would set the store as the default one in the group policy.

Thanks again for your help. I'll close the issue.
