### ISSUE TITLE
Get-PasswordFilterResult working but not actual AD filtering

### ISSUE THREAD

**Issue by ctdhr** [lithnet/ad-password-protection#29]
Hello,
I'm carrying out tests on my organisation's staging environment's AD Domain Controllers.
I have installed LPP through SCCM (along with the .admx files) on one DC (we have more than 10 DCs) and followed the Wiki and the very helpful blog posts.
I am however not able to filter out bad passwords when resetting a password through the AD console. Get-PasswordFilterResult works great though.

## Testing environment

* Windows Server 2012R2 DC, sync'ed with many other DCs
* Windows Management Framework 5.1 installed
* LPP executable v1.0.7143 (full install)

### ADMX files
When LPP got installed on this DC, the .admx files were placed in the default PolicyDefinitions folder. I copied them over to the Sysvol PolicyDefinitions folder. They were successfully sync'ed across all DCs.

### GPO configuration

Then, I created a GPO and linked it to the "Domain Controllers" OU. The Default Domain Policy contains some settings about password security (length, complexity, history etc.).

![issue_lpp_1](https://user-images.githubusercontent.com/12020172/66213763-b7024780-e6c0-11e9-9f92-de580518ab6e.png)

I configured this GPO with the settings provided by the .admx files.

![image](https://user-images.githubusercontent.com/12020172/66214097-5f181080-e6c1-11e9-8f5f-34167be95570.png)

I set the following scope for the GPO.

![issue_lpp_2](https://user-images.githubusercontent.com/12020172/66214353-d6e63b00-e6c1-11e9-95a4-de6357de61a9.png)

### Testing with Powershell

```
PS C:\Users\ctdhr> Import-Module LithnetPasswordProtection

PS C:\Users\ctdhr> Import-BannedWords [MY OWN BANNED WORD TEXT FILE]

PS C:\Users\ctdhr> Test-IsBannedWord "password"
True

PS C:\Users\kdaher> Get-PasswordFilterResult -Password "password-19" -Username "Testy" -Fullname "Testy McTestface" 
BannedNormalizedWord

PS C:\Users\ctdhr> Get-PasswordFilterResult -Password "Myusername_is_great" -Username "Myusername" -Fullname "Myusername Infull"
ContainsAccountName

PS C:\Users\ctdhr> Get-PasswordFilterResult -Password "Infull" -Username "Myusername" -Fullname "Myusername Infull"
ContainsFullName
```

Testing with Powershell is working out great so far.

### Testing in the AD console

I tried to reset my own password with the filtering enabled.
![image](https://user-images.githubusercontent.com/12020172/66214901-d9956000-e6c2-11e9-81b9-f164fae812d8.png)

Typed in "Password123" which should definitely get banned.

![image](https://user-images.githubusercontent.com/12020172/66214958-ec0f9980-e6c2-11e9-90b0-86ad12ef6272.png)

And the change works, even though it should not.

![issue_lpp_3](https://user-images.githubusercontent.com/12020172/66215055-182b1a80-e6c3-11e9-9941-ffa7d6caa6b0.png)

### Expected behaviour

The DC should have refused my password change request because "Password123" contains a banned normalized word.

### The logs
Whenever I run a `Get-PasswordFilterResult`, I get a log in the Event Viewer from LPP.
![image](https://user-images.githubusercontent.com/12020172/66215181-545e7b00-e6c3-11e9-882a-290f7caf1c6b.png)

But when I requested a password change for my account on the AD console, LPP did not produce any logs.
The regular Windows security auditing "4724 Password change requested" event popped out though.
Clearly, the DC is not requesting LPP's help on this matter.

### What I tried

I looked into the other DC's logs, and I could not find any password change requests. It was the DC which has LPP installed that processed the password change.

I tried disabling the Default Domain Policy's password complexity setting, but LPP still did not process the password change.

I tried changing the scope of the GPO to include my own specific account. It did not work.

### Despair
I'm clearly missing something, but I'm all out of ideas at the moment. Any help would be greatly appreciated. 

Thanks a lot

**Comment by ryannewington** [comment]
@ctdhr,

Thanks for the very detailed issue report. It's very helpful and helps zero in on the cause.

As you suspected, the DC is not calling the LPP binaries when processing a password change. 

You group policy is set up correctl. As it is a machine policy, it only needs to be scoped to the DCs themselves to apply. 

We need to determine why LSASS is not loading the plugin. This happens at boot time. Are there any errors in the event log around the time of booting that indicate LSASS having issues with loading the plugin?

Ryan

**Comment by ctdhr** [comment]
Hello @ryannewington,
Thanks for your quick response. I'm not able to debug this issue at this moment. I will post back whenever I have time to work on this matter again.
Cheers
