### ISSUE TITLE
Compare passwords to other users

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/ad-password-protection#31]
1. Would it be possible to compare the password during a change to other users? 
2. Would it be possible to compare the password during change to other users but matching the specific criteria? 

While the 1st point is a bit risky, for 2nd point the goal would be to prevent using same password by the same user for multiple accounts:
- admin.user
- super.user
- computers.user
- whatever.user 

Basically a way to prevent user using the same password that he has on his other accounts.

**Comment by ryannewington** [comment]
Hi @PrzemyslawKlys,

I understand where you are coming from, but I wouldn't bulid this capability into LPP. It's a very expensive operation to pull out and compare password hashes, and performance needs to be top priority. 

From a policy perspective, I understand why you wouldn't want those accounts to share a password. I'd recommend looking into the DSInteral PowerShell module, which will allow you to extract password hashes and compare. You could script this up to run on a DC once a day. You could then decide if you want to email them, force a password change on one of the accounts, etc. There's even a cmdlet that does do a duplicate check.

https://github.com/MichaelGrafnetter/DSInternals/blob/master/Documentation/PowerShell/Test-PasswordQuality.md#test-passwordquality

Sorry I'm not able to accomodate this request, but I hope the information provided helps.

**Comment by PrzemyslawKlys** [comment]
I already use that module, but it's reporting, not prevention. But I understand your concerns.
