### ISSUE TITLE
improve normalisation

### ISSUE THREAD

**Issue by EnviableOne** [lithnet/ad-password-protection#34]
Link to Hashcat's [leetspeak rule](https://github.com/hashcat/hashcat/blob/master/rules/leetspeak.rule): these 21 are the most common password substitutions used and should increase the hitrate on banned words. 
For those not uptodate on hashcat syntax, s is the substitute directive and the following character is substituted for the one following so sa4 is swap a for 4
this rulle would generate a couple of normalisation candidates, 9 could be g or q, and if adding the missing to the current rule set 6 can be b or g

**Comment by ryannewington** [comment]
I like the concept. 

There’s definitely improvements to make to the normalisation process. I’m tracking those improvements for the next release in #24 if you want to follow that post

I’ll add your notes there, and be sure to follow that issue for updates.
