### ISSUE TITLE
Administrative Templates not installed for domain

### ISSUE THREAD

**Issue by toddcbrown-btl** [lithnet/ad-password-protection#37]
I have run the complete install on all of the domain controllers in our domain. The PowerShell commands are working well.  We have reached the point of implementing group policies. When I go into Group Policy Management the Lithnet "Computer Configuration\Policies\Administrative Templates\Lithnet" does not exist.  How can I get them in place for the domain?

**Comment by toddcbrown-btl** [comment]
I have installed the application on a different box and copied the ADML and ADMX files to the 
\\DOMAINNAME.local\sysvol\DOMAINNAME.local\Policies\PolicyDefinitions\en-us
\\DOMAINNAME.local\sysvol\DOMAINNAME.local\Policies\PolicyDefinitions

As it stands the policies now show up. The tests will occur over the next few days.  I will keep you informed.

**Comment by ryannewington** [comment]
@toddcbrown-btl apologies for the delay in getting back to you. I'm glad you've found the solution. This is in the documentation, but I'll look to make this a bit more obvious, as many people run into the same issue.
