### ISSUE TITLE
An error was detected during parsing: DTD is prohibited

### ISSUE THREAD

**Issue by SashkaNebesny** [lithnet/ad-password-protection#39]
Hello.
When you open a group policy template, it displays a message: 
`An error was detected during parsing: DTD is prohibited \\consto.com\Policies\PolicyDefinitions\lithnet.activedirectory.passwordfilter.admx row 7, column 9`

`An error was detected during parsing: DTD is prohibited \\consto.com\Policies\PolicyDefinitions\lithne.admx row 7, column 9`
windows server 2019 core, forest level active directory 2016

And because of this error, the templates do not open

**Comment by ryannewington** [comment]
@SashkaNebesny 

How did you obtain these files? If you downloaded them with your browser, they may have been saved in HTML format instead of XML. Try copying them from the PolicyDefinitions folder of the machine where you installed the MSI.

**Comment by ryannewington** [comment]
Feel free to reopen this issue if it is still a problem for you
