### ISSUE TITLE
bannedwords number's sequences

### ISSUE THREAD

**Issue by haidepc** [lithnet/ad-password-protection#41]
I have tried to include on bannedwords number's sequences like "12345" or years "2020" but it doesn't work. Exemple "password2020"
Is there someway to include "numbers"?

**Comment by ryannewington** [comment]
@haidepc at this stage, no there isnt. Banned words are used to prevent passwords based on common words and well-known substitutions, so adding 'password' would block 'password2020', but adding numbers to the banned word store wont achieve what you are looking for.

**Comment by haidepc** [comment]
thank you for your reply.
Finally I have tried with regular expressions and It's working .
Exemple:
Passwords that contains Years from 2010 to 2099 or 123
^((?!20[1-9][0-9])(?!123).)*$

**Comment by ryannewington** [comment]
Ah! Great idea! A very creative solution.

**Comment by dm2746374** [comment]
That regex is just a line in your bannedwords store? Works ok? Pretty slick

**Comment by ryannewington** [comment]
The regex goes in the group policy. There's a specific entry for preventing passwords based on a regular expression

**Comment by ryannewington** [comment]
If you need any additional help with this, then just reopen this issue.
