### ISSUE TITLE
Changing Store Path, Finding what is used

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/ad-password-protection#42]
Hi,

I'm just testing your library in test environment before I deploy on production. I've done default installation without changing anything, copied GPO to policy store, and enabled required settings.

That part is working. Then I started to play with banned words 

```powershell
Import-Module LithnetPasswordProtection
Open-Store -Path "C:\Windows\SYSVOL\domain\scripts\SettingsFilter"

$Words = @(
    'Autumn'
    'Summer'
    'Winter'
    'Spring'
    'June'
    'July'
    'August'
    'September'
   'Password'
)

foreach ($Word in $Words) {
    Add-BannedWord -Value $Word -Verbose
}

Test-IsBannedWord 'Password'
```

And that works, but since I didn't change the path during installation now I'm having hard time applying that banned store to production use. I can't see any PS cmdlet that would allow changing the path (I could probably write one if I knew where that changes). I tried rerunning the installer, picked Change option, and replaced the store path to the path from above, but nothing changed even after a reboot. I actually retried running installer 3 times and the path is always the default one.

It seems the only way to change the store path is uninstall, reboot, install back, give proper path, reboot? Is that so, or can be it changed on the fly?

**Comment by ryannewington** [comment]
@PrzemyslawKlys you can modify the path by editing the following reg key

`HKEY_LOCAL_MACHINE\SOFTWARE\Lithnet\PasswordFilter\Store`

It will require a reboot of the server for the LSA filter to pick up the new path.

As a side note, I'd strongly recommend using a path other than SYSVOL on your DCs. Large SYSVOL volumes can cause replication problems and issues bringing DCs online.

Ryan

**Comment by PrzemyslawKlys** [comment]
Thank you. As for the SYSVOL I wondered why you mentioned this in installation instructions. I don't plan using banned hashes at this moment, just banned words so the SYSVOL will stay very small. Unless you see it being a problem too?

If that need arises I'll make sure to move it out, now that I know where it is changable

**Comment by ryannewington** [comment]
If your store file stays small it should be ok. 

When fully populated, the store can be up to 32k small files which isn't great for sysvol to have to deal with. As the DCs have dfs-r capabilies, I just recommend using a dedicated replication group to minimise the risk of replication issues on sysvol.
