### ISSUE TITLE
Can not import powershell module

### ISSUE THREAD

**Issue by VN1977** [lithnet/ad-password-protection#45]
My error looks like this
> PS C:\Windows\system32> Import-Module LithnetPasswordProtection
> Import-Module : Не удалось загрузить файл или сборку "DSInternals.Replication.Interop.dll" либо одну из их зависимосте
> . Не найден указанный модуль.
> строка:1 знак:1
> + Import-Module LithnetPasswordProtection
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileNotFoundException
>     + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
I have installed module DSInternalsbut and got a success. My native language  and language of OS is Russian.
But why do I get suach an error?

**Comment by ryannewington** [comment]
@VN1977 you shouldn't need to install anything else. The package includes the DSInternals library. Can you enable fusion logging and provide the resulting log file. Note you will need to close all PowerShell windows (or reboot) after setting these registry keys and before reproducing the issue

https://stackoverflow.com/questions/255669/how-to-enable-assembly-bind-failure-logging-fusion-in-net

**Comment by VN1977** [comment]
I tried to reproduce the problem at another domain controller and could not. So I just reinstalled LPP on problem DC and everything works OK.
