### ISSUE TITLE
SSO Loop - Anyone else

### ISSUE THREAD

**Issue by ChrisM65** [lithnet/ad-password-protection#50]
We are using docstar document management. After installing the password filter on our DC's (nothing configured, just install and reboot) our SSO for docstar was failing with a "Too many automatic redirects" error. Anyone else experience anything similar? Going to open a ticket with docstar also. Wanted to check here as well.

**Comment by ryannewington** [comment]
Hey @ChrisM65. These two things don't seem like they can be related. LPP hooks into the password change routine on the DC, nothing sense. It's only activated when a password change is being processed.

**Comment by ChrisM65** [comment]
That was my thought as well. It is odd, as soon as we removed it the sso issue went away. Still waiting to hear back from docstar. Appreciate you taking the time to respond.
