### ISSUE TITLE
ADMX templates missing from installation?

### ISSUE THREAD

**Issue by infinite-ideation** [lithnet/ad-password-protection#51]
I'm following the tutorial however after installing the LPP msi, the ADMX templates are not created either in the program files directory, the DFSR replication group directory on the DC (W2K19-1809), or the PolicyDefinitions directory. I ran the installer locally on my laptop (W10-1909) and experienced the same issue both as a domain admin / local admin. I was able to find them by downloading the source .zip, but I believe the installer that's supposed to copy the files into the installer directory may not be working, at least in my case.

**Comment by ryannewington** [comment]
Hi @infinite-ideation 
They should have been placed in c:\windows\policydefinitions 

Are they not there? The installer should have failed if it was unable to copy them.

**Comment by infinite-ideation** [comment]
> Hi @infinite-ideation
> They should have been placed in c:\windows\policydefinitions
> 
> Are they not there? The installer should have failed if it was unable to copy them.

Hey Ryan,

Sorry about that, definitely PEBKAC. I was looking under sysvol, not the local windows policy definitions folder. Verified they were indeed created. Thanks for the update!
