### ISSUE TITLE
Missing GPO after Installation

### ISSUE THREAD

**Issue by MaievJL** [lithnet/ad-password-protection#52]
Just completed installation on the active directory server by following this guide.

https://blog.lithnet.io/2019/01/lppad-1.html

I'm currently on this step.
_Give the policy an appropriate name when prompted, then right-click the policy, and select Edit. If you are not ready to make the policy live at this stage, right-click the policy, and untick Link Enabled.

Navigate to Computer Configuration\Administrative Templates\Lithnet\Password Protection for Active Directory\Default Policy_

However, I cannot see the policy on my Group Policy.

I also checked C:\Windows\PolicyDefinitions and I saw lithnet.activedirectory.passwordfilter.admx and lithnet.admx, as their respective ADML under en-us of that folder. 

Somehow the group policy isn't showing up. I've also restarted as well.

I'm on Windows Server 2019 with the 2016 domain functional level. Thank you!

**Comment by ryannewington** [comment]
@MaievJL , 

Try copying the ADMX and ADML files into the central policy store of the domain. https://github.com/lithnet/ad-password-protection/wiki/Configure-group-policy

Although they should definitely be appearing if they are installed on the local machine

**Comment by MaievJL** [comment]
@ryannewington 

Thank you for the tip. I ended up copying the files from

C:\Windows\PolicyDefinitions to <-- keep thinking this is the central policy store. 
C:\Windows\SYSVOL\sysvol\contoso.local\Policies\PolicyDefinitions

And the GPO now sees it. Cheers!
