### ISSUE TITLE
Doesn't seem to check Imported passwords

### ISSUE THREAD

**Issue by Jebbus82** [lithnet/ad-password-protection#53]
Password protection appeard to install and import HIBP hashes ok. Event logs suggest it's started fine which is confirmed by the event log stating that a users password was checked and was ok, the issue is the password used was on the HIBP list and in the compromised list, this is also the same when using the  Test‐IsCompromisedPassword PS cmdlet on the same password. For referecen the password was "password123"

**Comment by ryannewington** [comment]
@Jebbus82 

The Test-IsCompromisedPassword cmdlet correctly rejected the password, or it let it through as well?

The LPP agent on the DC will approve password changes if it can't access the store or its pointing to an empty location. Does the DC's SYSTEM account have read access to the password store folder and subfolders?

**Comment by Jebbus82** [comment]
@ryannewington 
Thanks for replying! So things started to work randomly the next day, the only thing I can think of is that it may have been some replication delay as there are 2 DC's maybe? though we did import the file separately onto each of them. At the time, the Test‐IsCompromisedPassword returned false on password123 but now returns true (as expected). Thanks again and thanks for making this, it's really neat!

**Comment by ryannewington** [comment]
@Jebbus82 yes that is possible. the DCs also hold open a cached handle to the store, so it the store wasnt there at the time it opened it, it may have hold onto it and approved passwords because they werent found in the 'non existent' store. I've got some better logging planned for the next version so this isn't so obscure.

Glad you got it working.
