### ISSUE TITLE
Errors not showing up in Event Viewer

### ISSUE THREAD

**Issue by rcallahan2** [lithnet/ad-password-protection#54]
Whenever I change a password and it successfully processes on say DC1 it it will show the standard information event in the event viewer.  However whenever the filter denies a password reset on example DC2 there are no informational or warning events.  So more or less some events are being logged and others essentially disappear into the ether.

**Comment by ryannewington** [comment]
@rcallahan2 

AD itself may be rejecting the password before it gets to LPP for filtering. In which case, there won't be the usual event logs.

Do you have any AD password policies in use as well as LPP policies?

Ryan
