### ISSUE TITLE
Trying to apply a regex rule [not match]

### ISSUE THREAD

**Issue by rocketscientist911** [lithnet/ad-password-protection#55]
I am trying these regex but no luck yet? maybe i am doing this wrong?

 ### should not consist of 3 digits at the end of the word.

`\d{3}$`
`\d\d\d$`
`[0-9]{3}$`

Events show its approved

The password set request for bakuru () was approved.

**Comment by ryannewington** [comment]
The first rule should work. To confirm, the group policy is applied to all domain controllers, right? Are other GPO settings working. Say if you change the minimum password length to 20, is it rejecting shorter passwords?

**Comment by rocketscientist911** [comment]
> The first rule should work. To confirm, the group policy is applied to all domain controllers, right? Are other GPO settings working. Say if you change the minimum password length to 20, is it rejecting shorter passwords?

Well, yes. That was the first thing i did to ensure i was not missing out on applying the policies. The password length ruled worked immediately with a GPUPDATE although the regex one didn't work so I thought maybe I am doing the regex in a wrong format? I am trying this on a test Windows Server 2019.

**Comment by ryannewington** [comment]
@rocketscientist911 

Sorry, I gave you some bad advice here. Your regular expression needs to match the whole string, not just part of it. So to match a password that ended with 3 or more numbers, use the following

`.+\d{3,}$`

The previous value we used would have rejected passwords that consisted only of 3 digits.

Hope that helps

Ryan

**Comment by ryannewington** [comment]
@rocketscientist911 did this resolve the issue for you?

**Comment by rocketscientist911** [comment]
Sorry, I thought I had replied to this thread.. I am closing this and thanks a ton.
