### ISSUE TITLE
Get words  added on banned list

### ISSUE THREAD

**Issue by haidep** [lithnet/ad-password-protection#57]
Is there some way to get words on banned list?

**Comment by jaysnrye** [comment]
@haidep you can find the answer to your question in the wiki.

https://github.com/lithnet/ad-password-protection/wiki/Add%E2%80%90BannedWord

**Comment by haidep** [comment]
I already review the wiki but I only saw how to add not how to get the words on the "banned list"
Maybe there is something that i missed....

**Comment by ryannewington** [comment]
@haidep adding words to the store is a one way trip. The words are hashed and stored for efficient retrieval and evaluation, so are not kept in plain text. 

You can test if a word is in the store using PowerShell, but of course you need to know the words you want test

**Comment by ryannewington** [comment]
Please reopen if you have any additional questions
