### ISSUE TITLE
Regex should match on substring, not the entire string

### ISSUE THREAD

**Issue by JulianBlu** [lithnet/ad-password-protection#59]
I want to prevent users from selecting a password with more than 4 repeating characters.
I've used (.)\1{4,} regex in the "Password must not match a specified regular expression" policy.

But it seems that adding even a single different character in the password spoils the filter.
The behavior is different from PowerShell match operator.

The following tests use regex as the only complexity requirement in policies.

PS C:\> 'aaaaaaaa' -match '(.)\1{4,}'
True
PS C:\> Get-PasswordFilterResult -Password "aaaaaaaa" -Username "test" -Fullname "Test"
MatchedRejectRegex

Now adding a 'b' Powershell still matches, PasswordFilter do not.

PS C:\> 'aaaaaaaab' -match '(.)\1{4,}'
True
PS C:\> Get-PasswordFilterResult -Password "aaaaaaaab" -Username "test" -Fullname "Test"
Approved

What I'm doing wrong?

**Comment by ryannewington** [comment]
Hi @JulianBlu 

Internally, the app uses the C++ regex standard `match` function, which looks to match the _entire_ string, not a part of it.

So the regex you want is actually 

`.*?(.)\1{4,}.*`

![image](https://user-images.githubusercontent.com/17229877/99893340-e4e68900-2cd2-11eb-9146-fc2dc58c9e51.png)

**Comment by ryannewington** [comment]
It's not the first time this has come up, so I'm going to convert this into an enhancement request for a future version to perhaps default to substring matching, as one probably expects based on how things like PowerShell work.

**Comment by tedingus72** [comment]
The one issue I have with this is that it will allow 1111X111.

**Comment by ryannewington** [comment]
See issue #60 for a build that contains regex partial matching by default

**Comment by ryannewington** [comment]
This issue has been resolved in the latest release https://github.com/lithnet/ad-password-protection/releases/tag/v1.0.7238
