### ISSUE TITLE
Lithnet not logging remote password attempts

### ISSUE THREAD

**Issue by mer0llac0aster** [lithnet/ad-password-protection#62]
Environment:
1 DC (Server 2019, 2016 functional level)
1 Windows 10 20H2 endpoint
Lithnet installed with HIBP database and BannedWords list
GPO configured and applied
All systems rebooted

Behavior:
Test 1. Lithnet logs startup message to Application log on boot up.

Test 2. Attempting to set a bad password on the DC with ADUC, Lithnet logs the events in the Application log.  

**Test 3: Attempting to reset password to bad passwords on endpoint. nothing is logged on DC or endpoint, however the policy is in effect as I cannot set a password that is a) compromised or b) in the banned words list. No errors or warnings reported, just nothing logged.**

Test 3: Installed lithnet on endpoint to see if if would log locally. It does not.  Uninstalled from endpoint

What do I need to do for Lithnet to log password changes on endpoints the same way it logs them locally?

**Comment by ryannewington** [comment]
Hi @mer0llac0aster 

The usual cause of this scenario is that the built-in Windows password policy filter is kicking in first, and rejecting the password change. When this happens, LPP never gets a chance to process the password, hence no logs. Especially check for things like minimum password age in your AD password policy.
