### ISSUE TITLE
duplicate logging of password change attempts on DC

### ISSUE THREAD

**Issue by mer0llac0aster** [lithnet/ad-password-protection#63]
Environment:
1 DC (Server 2019, 2016 functional level)
1 Windows 10 20H2 endpoint
Lithnet installed with HIBP database and BannedWords list
GPO configured and applied
All systems rebooted

Steps to reproduce:
Step 1. Lithnet logs startup message to Application log on boot up.

Step 2. Attempt to set a bad password (banned word normalized) on the DC with ADUC.

Outcome: i get 4 total events every time i attempt to set the bad password.  Event ID 4 followed by Event ID 8205 followed by another Event ID 4 followed again by a second Event ID 8205
![image](https://user-images.githubusercontent.com/11506435/111487672-f1be3b00-870e-11eb-9aec-44e53067fa46.png)

**Comment by ryannewington** [comment]
@mer0llac0aster this one is a known issue. It's not a fault with LPP as far as I can tell. Windows is sending the password through twice.
