### ISSUE TITLE
Full username in password with leetspeak

### ISSUE THREAD

**Issue by evertonbernardi** [lithnet/ad-password-protection#66]
Hello there! First of all I want to thank you for making such a great tool.

I've identified a potential flaw in the policy "_Reject passwords that contain the user's display name_" mechanism or in the "_Reject passwords found in the compromised password store_".
Here you can find how my policies are configured in a test environment:

![GPO Settings](https://user-images.githubusercontent.com/6811762/137483107-29e83f25-6158-4991-8c8e-d92a5e8ce2f8.png)

I've added all of the words of my own name to the banned word store:
![image](https://user-images.githubusercontent.com/6811762/137483783-f9a298b3-0b12-4538-8fab-86cf1cdf956b.png)

If I test the password "3ver+on 8runo 8ern@rdi" against my own username it gets approved as you can see in the image bellow:

![image](https://user-images.githubusercontent.com/6811762/137483866-9549a031-517f-4e82-b44f-7744e79c67fd.png)

Is this expected? If so is there a way I can deny a user from getting a password like this approved?

Best regards!

Everton

**Comment by PrzemyslawKlys** [comment]
@ryannewington Could it be enabled so the banned word store would effectively ban the usage of banned words altogether? While i understand the normalization process the company rules often say - "Dont use XYZ in your password", and then someone comes in and uses XYZ_OnAHill and it works :/

**Comment by ryannewington** [comment]
@PrzemyslawKlys unfortunately not. The words in the banned word store are stored using a one-way hash, so we don't actually have the plain-text version of the banned word to check against. You'd have to use regex to block passwords with specific words in it.

**Comment by PrzemyslawKlys** [comment]
Could there be another store added? :-) what is the length of accepted regex?
