### ISSUE TITLE
Second DC - UNC share

### ISSUE THREAD

**Issue by gorbiWTF** [lithnet/ad-password-protection#69]
I have only used one domain controller so far and Password Protection worked fine. But now I have a second DC so I created a UNC share to the store (_\\\dc1\store$_ points to _C:\Program Files\Lithnet\Active Directory Password Protection\Store_ on DC1). Then I reinstalled Password Protection (ran into the same problem as #61) on DC2 with the correct path.

However it still doesn't seem to find the store. Passwords get correctly blocked based on length (as configured) but even `Test-IsCompromisedPassword -Value password` returns _False_ (not blocked). What am I missing?

**Comment by ryannewington** [comment]
Did you grant DC2$ read permission to the share and the underlying directory on DC1?

Also, after changing the store location, you must always reboot the DC.
