### ISSUE TITLE
MSI file agent automated deployment via Group Policy

### ISSUE THREAD

**Issue by zibs1** [lithnet/ad-password-protection#70]
Is there anyway we can automate msi agent deployment on DCs via GPO with pointing to UNC store path? The use case would be to have new DC added.

**Comment by ryannewington** [comment]
@zibs1 

Yes, there shouldn't be any issue with using standard MSI commands to do a silent install. You can use the MSI property `STOREDIR` on the command line to set the store path.

Alternatively, you can export the `HKLM\Software\Lithnet\PasswordFilter` from a working machine and import it as part of your build.

**Comment by zibs1** [comment]
thanks @ryannewington 
We tried to simplify things with creating mst modification file and attach to software deployment msi file in GPO but we failed to address this, so we end up using script with msiexec with parameters. Here is the code below:
```
$File='\\DOMAIN\LPP\lpp.msi'
$StoreParam='STOREDIR=\\DOMAIN\LPP'
`msiexec /L*V $Log /i `"$File`" /qn /quiet /norestart $StoreParam"`
```

**Comment by ryannewington** [comment]
Glad you got it working!
