### ISSUE TITLE
issue with importing banned words

### ISSUE THREAD

**Issue by Brucew-dtr** [lithnet/ad-password-protection#71]
Hi, I am try to use the import-bannedwords and the import-compromisedpasswords commands to import a text file containing passwords with the format being one password per line .

Here are the commands I am using 
import-bannedwords -filename "C:\Temp\AD_Password_Exclusion_List.txt"
import-compromisedpasswords -filename "C:\temp\AD_Password_Exclusion_List.txt"

attached is the text file containing my passwords.
[AD_Password_Exclusion_List.txt](https://github.com/lithnet/ad-password-protection/files/8313090/AD_Password_Exclusion_List.txt)

If the text file format is incorrect can you please advise the correct format and update the wiki with an example of the test file format so that others do not have the same issue.

In general I am very impressed with the Lithnet AD Password Protection module and I appreciate your work.

Thanks, Bruce

**Comment by ryannewington** [comment]
Hey Bruce, that file format is correct. It's just one word per line. 

Is it not working? Are you getting an error message?
