### ISSUE TITLE
How to enter multi-line regular expressions

### ISSUE THREAD

**Issue by miumiug** [lithnet/ad-password-protection#72]
How to enter a multi-line regular expression in the input box at “Passwords must not match a specified regular expression”
![image](https://user-images.githubusercontent.com/15625231/159438586-9307d8c2-917b-43d1-9f03-7eb6f5946281.png)

**Comment by ryannewington** [comment]
I'm not quite sure I understand the ask here. Do you want to be able to add multiple different regular expressions?

**Comment by miumiug** [comment]
> want

Yes, want to be able to add multiple different regular expressions.

**Comment by miumiug** [comment]
> I'm not quite sure I understand the ask here. Do you want to be able to add multiple different regular expressions?

Yes, want to be able to add multiple different regular expressions.

**Comment by ryannewington** [comment]
You'll need to combine them into a single regular expression using the OR operator

**Comment by miumiug** [comment]
> You'll need to combine them into a single regular expression using the OR operator

Thank you very much!
