### ISSUE TITLE
Remove common word delimiters to prevent weak passphrases

### ISSUE THREAD

**Issue by jonod8698** [lithnet/ad-password-protection#73]
Some of our users figured out a way to bypass the filter. They can use commas between weak words. 

For example: zero,five,zero and password,password,password bypasses the filter with haveibeenpwns list + zero-nine added manually.

![image](https://user-images.githubusercontent.com/51128479/159448234-cc92212b-e4ab-44d3-b5e9-80cccde8dc54.png)

Looking at [stringnormalization.cpp](https://github.com/lithnet/ad-password-protection/blob/master/src/PasswordFilter/stringnormalization.cpp) and [stringnormalization.h](https://github.com/lithnet/ad-password-protection/blob/master/src/PasswordFilter/stringnormalization.h), it should be possible to add some special characters to CHARS_TO_DELETE to prevent this scenario.

The downside is a mixed weak word and random password such as password!@#&(!*$@#$$@@#&^&,.@#, would be rejected if you removed all special characters. So only a minimal set of common delimiters should be included.

A similar issue was raised [here](https://github.com/lithnet/ad-password-protection/issues/20).

I've blocked some time next month to play around with the defaults and compile my own version and test against hashcat. Will get back with any findings. But I am curious, is there a specific reason why [CHARS_TO_DELETE](https://github.com/lithnet/ad-password-protection/blob/master/src/PasswordFilter/stringnormalization.h) only contains "_ . +" ?

Thanks for your hard work btw :)  Happy to report we've dropped our crackable passwords with standard hashcat rules from 50% to 10% in 1 year!!

**Comment by ryannewington** [comment]
@jonod8698 

You're right, in that adding too many delimiters to remove may start causing problems.

At the end of the day, its about finding the balance. We decided on the characters by analyzing existing breached passwords for common patterns, and looking at common substitutions that cracking tools expect people to use. That's how we came up with our algorithms.

Using those words isn't a problem on its own - We know that passwords users choose are going to be based on words. We're only trying to prevent them using those words in a way that makes its trivially easy for an attacker to break. In our analysis at the time, comma-separated word patterns were not something that appeared in the dataset to a significant degree. As an attacker if I _knew_ users in your organization were using patterns based on comma separation, then I could use that information to create my own dictionary to reduce my attack time. But given a random password hash, from a random organization, I'm not sure thats a common one I'd consider.

The normalization function's purpose is to reveal cases where a user has turned a single word into a 'clever' (from their perspective) password by doing the usual `p@ssw0rd!!!!` type things. It's not designed to prevent users from using dictionary words at all. Just from using them in predictable ways.

**Comment by jonod8698** [comment]
@ryannewington

Agree with most of the above! It's definitely tricky to balance and I have to always remind myself it's defense in depth so no solution is perfect.

That being said, it's kind of sad to see all of our recent new users with password like "One,Two,Seven", "Two2Four4Zero0". But as you mentioned, without knowing beforehand what patterns are used, an attacker with general wordlists and masks would find it difficult to guess.

If there's scope in the future to add an extensible way to alter the CHARS_TO_DELETE that would be awesome. I imagine it would require significant changes, given there are code-signing requirements.

**Comment by ryannewington** [comment]
@jonod8698 

It could be an option to make it extensible, but I think even if you included comma in the list, `One,Two,Seven` becomes `OneTwoSeven` which would only get rejected if that was in the HIBP dataset. Word normalization is not going to pick that up. If it did, we'd end up blocking passphrases that we want people to use.

Then again, if you added comma to the list, and it did do what you want, whats to stop users choosing another character instead of comma?

You could stamp out the comma behaviour today by using a reject regex that looks for words separated by commas. But I think youd end up playing a cat-and-mouse game.

**Comment by jonod8698** [comment]
@ryannewington 

Using words as numbers is a specific issue as there's a limited number of 3 number-words - quite easy to guess.

Perhaps this isn't a technical issue to solve - as you said, it's a cat and mouse game. A password filter is just one mitigation. 

I'll explore some other solutions in addition:
- User education
- Policy
- Minimising availability of offline fast hashes like NTLM

Thank you for your help!

**Comment by ryannewington** [comment]
Hi @jonod8698 

Good point. As there is a limited combination of 3 number words, you could do up a PowerShell script to generate these and add them directly to the banned password database?

**Comment by jonod8698** [comment]
@ryannewington 
Will do :) I've done it for comma delimited number words, but probably need to extend it to other common delimiters.
