### ISSUE TITLE
Import-CompromisedPasswordHashes -> Found 0 objects....

### ISSUE THREAD

**Issue by dimforensics** [lithnet/ad-password-protection#76]
when i'm trying to import a hash from a file, it doesnt import by showing "Found 0 objects. Committed 0 new records and discarded 0 duplicates".

Import-CompromisedPasswordHashes -Filename "D:\hash.txt"

**Comment by ryannewington** [comment]
Hi @dimforensics 

What does the file format look like?

An example of the correct format is here 
https://github.com/lithnet/ad-password-protection/wiki/Import%E2%80%90CompromisedPasswordHashes#filename

**Comment by dimforensics** [comment]
Hi Ryan,
![sdsdsd](https://user-images.githubusercontent.com/29274096/170227036-f3c5dd9d-189f-4c71-a143-bcfebf90e979.PNG)

**Comment by ryannewington** [comment]
Can we check to see if it actually added the hash? It might just be that the update happened before the UI had a chance to update stats. Replace the hash below with your hash

```
$hashString = '8846f7eaee8fb117ad06bdd830b7586c'
$hashByteArray = [byte[]] ($hashString -replace '..', '0x$&,' -split ',' -ne '')
Test-IsCompromisedPassword -Hash $hashByteArray
```

**Comment by dimforensics** [comment]
actualy, after executing with my hash:
$hashString = '8f01862ff171fcacf7c3951a5ec034a3'
$hashByteArray = [byte[]] ($hashString -replace '..', '0x$&,' -split ',' -ne '')
Test-IsCompromisedPassword -Hash $hashByteArray
,
it shows "True"

**Comment by ryannewington** [comment]
Ok, so the hash got added and is in the store.

Have you looked at the user's actual password hash to make sure it is what you expect it to be? You can use the DSInternals module to get the current hash value https://github.com/MichaelGrafnetter/DSInternals/blob/master/Documentation/PowerShell/Get-ADReplAccount.md

**Comment by dimforensics** [comment]
My fault, found the problem, this password hash dumped from AD last week, and the User changed the password yesterday :)
Thanks Ryan for the fast support.
