### ISSUE TITLE
Custom Password Complexity Requirement Message when can not change the password

### ISSUE THREAD

**Issue by dimforensics** [lithnet/ad-password-protection#77]
Can you include a functionality in the app "Lithnet" with a custom message for user that cannot change the password because of ....? When a user changes their password, sometimes they are denied because it does not meet the Domain’s password complexity requirements. Unfortunalty the error message does not tell them WHAT the requirements are. 
Or you may know the workaround in Windows?!

**Comment by ryannewington** [comment]
@dimforensics This is a bit of a pain-point with any password filter. Unfortunately, Microsoft only provide a single error code when a password is rejected. This is why we get the cryptic message, even when not using LPP

```Unable to update the password. The value provided for the new password does not meet the length, complexity, or history requirements of the domain.```

Unfortunately, there isn't anything we can do to improve this, as it's baked into Windows itself.

**Comment by dimforensics** [comment]
Thanks Ryan for the response. 
Hopefully, they will do some changes in near future.
