### ISSUE TITLE
Test-IsADUserPasswordCompromised fails with CRC check failed

### ISSUE THREAD

**Issue by maxferrario-msf** [lithnet/ad-password-protection#81]
Hi,
I'm scanning our AD using the script found at https://github.com/lithnet/ad-password-protection/wiki/Audit-existing-passwords from a trusted workstation.
Every now and then, I get the following error (this is the output of $error[0].Exception.ToString()) 

> System.FormatException: CRC check failed.
>    at DSInternals.Common.Validator.AssertCrcMatches(Byte[] buffer, UInt32 expectedCrc)
>    at DSInternals.Replication.ReplicationSecretDecryptor.DecryptSecret(Byte[] blob)
>    at DSInternals.Common.Data.DSAccount.LoadHashes(DirectoryObject dsObject, DirectorySecretDecryptor pek)
>    at DSInternals.Replication.DirectoryReplicationClient.GetAccount(Guid objectGuid)
>    at Lithnet.ActiveDirectory.PasswordProtection.PowerShell.TestIsADUserPasswordCompromised.ProcessRecord() in D:\dev\git\lithnet\ad-password-protection\src\PasswordProtectionPS\TestIsADUserPasswordCompromised.cs:line 59
>    at System.Management.Automation.CommandProcessor.ProcessRecord()

Printing the $user variable, I noticed that this happens every time with different accounts, and if I manually run the Test-IsADUserPasswordCompromised scriptlet one one of those accounts I get a valid response, i.e. no errors.

Any idea of what's going on?

Thanks,
Massimo

**Comment by ryannewington** [comment]
Hmmm... there is something strange going on with the DSInternals library we use to get the hash. Can you confirm which version of LPP you are running? We released an update last month to fix another issue with DSInternals

If you download their PowerShell library, and check the result of this command against a failing user, do you get the same error?

https://github.com/MichaelGrafnetter/DSInternals/blob/master/Documentation/PowerShell/Get-ADReplAccount.md

**Comment by maxferrario-msf** [comment]
Hi Ryan,
I installed the MSI yesterday, so I guess this is the latest version: according to the file properties, it was created on 06/25/2022 at 3:19 AM and its revision number is {42339301-7A86-4A14-8BB9-8A4353A7DC93}.

LithnetPasswordProtection.psd1 says:

```
#
# Module manifest for module 'LithnetPasswordProtection'
#
# Generated by: Ryan Newington
#
# Generated on: 28/08/2015
#

@{

# Version number of this module.
ModuleVersion = '1.0.7239.0'

# ID used to uniquely identify this module
GUID = 'e6a12c2f-7a92-44af-9ec8-6473d479cf27'
```


As for the testing DSInternals PS library on failing users, as I said the errors are not repeatable: if I run the script twice I get errors on different accounts, and if I run Test-IsADUserPasswordCompromised manually on the failing accounts I do not get an error.

I added a 5 seconds pause between each call, but I only managed to decrease the number of errors. 
I guess this has probably something to do with my DC refusing to answer too many questions in a short period of time, and that the cmdlet / library is working as expected: what do you think?

Massimo

**Comment by maxferrario-msf** [comment]
Thanks!
