### ISSUE TITLE
LSA protected mode working?

### ISSUE THREAD

**Issue by Alex-Busch** [lithnet/ad-password-protection#83]
I know that since version [1.0.7236] the support of LSA protected mode should be given. 
However if I try that, it doesn't succeed. It gives error 577 on load of lithnetpwdf in systemlog.
The corresponding log entry in Code Integrity is related to the required VCRuntime. But this is already version 14.32.31332 which is quite up to date.
`Code Integrity determined that a process (\Device\HarddiskVolume2\Windows\System32\lsass.exe) attempted to load \Device\HarddiskVolume2\Windows\System32\vcruntime140.dll that did not meet the Microsoft signing level requirements.`
So I wonder if anyone got that running?

Best regards
Alex

**Comment by ryannewington** [comment]
Hi Alex,

We're not seeing this in our environments, but have another open case when a user is seeing this one on of their DCs but not the other. What does the signature on vcruntime140 look like?

![image](https://user-images.githubusercontent.com/17229877/184018924-0169c881-4287-4bd2-8a3a-dd17e46e8ef4.png)

Can you provide me with some information on the OS version and build number?

**Comment by Alex-Busch** [comment]
Hi Ryan,
thank you for your answer. Sure, here you got some details.
### System 1:
Windows 2012R2 Datacenter, german language, running on VMware
![image](https://user-images.githubusercontent.com/110817826/184081284-8e7d5fc8-fed9-4dde-9d79-77d399c08a88.png)
The vcruntime details:
![image](https://user-images.githubusercontent.com/110817826/184080906-efcd382e-e100-46a7-a12c-7b2efdaed1d7.png)
![image](https://user-images.githubusercontent.com/110817826/184080974-99c72af2-abc7-4e31-aa08-36923da6259b.png)
![image](https://user-images.githubusercontent.com/110817826/184081855-f3c4197e-0ee5-4927-b62e-278e36bfb806.png)


### System 2:
Windows 2016 Standard, german, running on VMware
![image](https://user-images.githubusercontent.com/110817826/184081173-02e47460-b172-4486-a438-3e75824c561a.png)
vcruntime is same as above.

Original there was an older vcruntime on the systems, which came with vmware tools. As I suspected a connection to that I updated to the latest release, but the issue persists.

Best regards
Alex

**Comment by ryannewington** [comment]
Hi Alex,

I've been able to reproduce this on Server 2012 R2. The issue doesn't seem to appear on Windows Server 2019. I'm still investigating what is going on, but there is definitely something up with that version of c runtime. I'm going to try making a new build and linking it to the latest c runtime. I'm currently having some EV signing certificate issues that I'm trying to sort out with my vendor, so it will be a few days before I have updates on this.

**Comment by ryannewington** [comment]
We've released a fix to workaround the issue with the Microsoft signing certificate

https://github.com/lithnet/ad-password-protection/releases/tag/v1.0.7242

**Comment by Alex-Busch** [comment]
Thank you for the update. It's working now as expected. I appreciate your work.
