### ISSUE TITLE
Passwords must not match a specified regular expression

### ISSUE THREAD

**Issue by Ghx011** [lithnet/ad-password-protection#85]
Hello,

I am having problems banning multiple specified regular expressions using the OR Operator.

This are the words i want to ban

Iphone
Motorola
Microsoft
Dell
Samsung

And this is the code i am using to ban the words

(?i)(\W|^)(Iphone|Samsung|Motorola|Microsoft|Dell)(\W|$)

![1](https://user-images.githubusercontent.com/111883060/186168686-2b1a978a-98b0-44a4-a32c-8e8b56218619.PNG)

Am i doing it right the OR Operator?
Because after i enter the code and update my group policy i can still enter these words as passwords.

What is the correct code for the OR operator for this words?

Thank you.

**Comment by Ghx011** [comment]
I can ban these words on powershell just fine, but i want to ban these words by using multiple different regular expressions.

Thank you.

**Comment by ryannewington** [comment]
Hi,

The syntax would be

`(?:iphone|samsung|microsoft|dell)`

Regarding performance, the longer the regular expression, the more CPU resources required, and the longer amount of time it will take to process a password change. As this is dependent on RAM, CPU, and existing server load, it's not possible for us to make an assessment on any limitations. I'd recommend gradually increasing the number of words, and testing each increment.

I would consider if the banned word feature would be more appropriate here. The goal is to prevent people from using known guessable passwords. It's very unlikely a user would have a password based on one of these words guessed if they used a non-standard pattern. eg `asdfasdfasdIPhoneasdfasdf`. The data shows us they are more likely to do something like iPhone2022 which is easily guessable, and it the type of thing the banned word filter is designed to prevent. Using a dictionary word in a password is not a security problem, in itself. Using it in a brute-force-able way, or a guessable way, certainly is. That's what we aim to stop. Perhaps a combination of the two is appropriate. Use regex to ban the words you are most concerned about, and use the banned word list for the rest?

**Comment by Ghx011** [comment]
Hello,

Thank you for your response, i will try to use more the Banned Word Lists.

However i have couple of questions  please.

1. I have set the settings of complexity for a password a user must have these 4:
-Uppercase Letter
-Lowercase Letter
-Number
-Symbol
A user in my domain should have this 4 required  for a strong password.

However, when i ban a word on Powershell for example the word Keyboard both on banned and compromised password.

I can still enter the password even though is banned.
![1](https://user-images.githubusercontent.com/111883060/186280998-b22ddb2f-6d89-4436-a57c-fed045c08ea6.PNG)

I think something is wrong with my settings can you help please?
My settings : 
![2](https://user-images.githubusercontent.com/111883060/186281045-60332a3b-03ff-4996-ae62-324eca5b8ee8.PNG)
![3](https://user-images.githubusercontent.com/111883060/186281050-ed9be2d0-61c9-43f1-8d32-4b5cb06c441d.PNG)

I think i did something wrong with the settings i am not sure, because before it worked.
I still want the settings that a user must complete all 4 points for a strong password in my domain.

Also what is the difference between
-Enable Length-based complexity rules
-Passwords Must meet specified number of complexity points

I think they both the same only the Enable Length-based complexity rules has more options.
I have enabled them both? Is there a problem? Should i turn one off?

Let me know please.

And thank you for this amazing program.

All the best !

**Comment by Ghx011** [comment]
Also another question for the banned word list
I have a ready list, it includes more then 50 Million Passwords. Its around 80 MB +
For the banned word list, will we  have a problem with the memory or the perfomance of the server?

Based on the list you pinned on the thread, the size of the list was more then 10 GB from haveibeenpwned password list.
So we wanted to try something more smaller to not affect the server.

Thank you !

**Comment by ryannewington** [comment]
Are those group policies applying to users, or the DCs? The policies for LPP need to apply to the domain controllers where LPP is installed, and it must be installed on every writable controller in the domain.

If it is, ensure you have event ID 3 on each domain controller from LithnetPasswordProtection which appears at reboot to tell you that the module was successfully loaded. There is a known issue at the moment where LPP may not load due to a recent update to the Microsoft Visual C runtime. We are working with Microsoft on this.

You can read more about the differences between length and points based complexity in these docs pages

https://docs.lithnet.io/password-protection/configuration/configuring-a-length-based-complexity-policy
https://docs.lithnet.io/password-protection/configuration/configuring-a-points-based-complexity-policy

The storage and search algorithm used for both banned words and banned passwords is the same. It is an extremely efficient implementation, and you don't have to worry about the practicalities of large stores. We have customers with stores over 60GB in size and its still very fast.

**Comment by Ghx011** [comment]
Okay thank you for your answer.

One last question please.

Can the compromised store and banned store have the same list?

For example
I have a big list
And i want it uploaded on banned store + compromised store.

Will that cause any issue or something?
Or im good to go?

Thank you once again.

**Comment by ryannewington** [comment]
They can be fed from the same sources. The banned word list is normalised befor being added.

So while adding p@ssw0rd to the banned password store blocks that exact password, adding the same value to the banned word store will result in it being converted to "password" and added. This then blocks any variant of "password" based on common substitutions
