### ISSUE TITLE
There was a problem opening the store file - event id 9,8

### ISSUE THREAD

**Issue by zibs1** [lithnet/ad-password-protection#86]
We are experience errors when password is processed, we are getting an event 9 and then 8 in windows event log, see below logs.
There is no indication on any network issues as we confirm this with our network team. It occurred on 2x different DCs in completely different sites on AWS and on prem. We are using Windows 2019 1809 x64, VC++ 2015-2019
Agents are on v1.0.7242 and we are using AWS FSx as a backend storage hosting.
What this error code 183 means and why event 8 indicating file already exists?
Any idea what other problem that could be related or where we could look further?

```
Log Name:      Application
Source:        LithnetPasswordProtection
Date:          9/22/2022 11:26:31 AM
Event ID:      4
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      DC-01
Description:
Processing a password set request for admin.
```

then

```
Log Name:      Application
Source:        LithnetPasswordProtection
Date:          9/22/2022 11:26:31 AM
Event ID:      9
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DC-01
Description:
There was a problem opening the store file. Check that the store folder exists and is accessible Error code: 183
```
then 

```
Log Name:      Application
Source:        LithnetPasswordProtection
Date:          9/22/2022 11:26:32 AM
Event ID:      8
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DC-01
Description:
An unexpected error occurred. Error code: 183 Message: Failed to create the store folder: Cannot create a file when that file already exists.
```

**Comment by ryannewington** [comment]
@zibs1 

I'm not too familiar with AWS FSx - the error code you see if being returned from that system. What permissions have you assigned to the file share? Does each DCs computer account have read access to the share _and_ all the files in it?

**Comment by zibs1** [comment]
@ryannewington that was it, I mean perms for DCs were likely missing, I'm not sure how we missed this? :/. We had slightly diff set up in other domain but we had read access for Authenticated Users, in new domain(the one we have issue) we only had read for SYSTEM and domain admins, once I adjust perms for Domain Controllers group we can se successful access. Many thanks!
