### ISSUE TITLE
Add package in chocolatey or winget

### ISSUE THREAD

**Issue by 1mm0rt41PC** [lithnet/ad-password-protection#88]
It would be very convenient to be able to install this wonderful tool via a package manager such as chocolatey or winget.

**Comment by ryannewington** [comment]
Hi @1mm0rt41PC 

Thanks for taking the time to make this suggestion. Winget would be the ideal platform for us, but it doesn't support Windows Server at this stage. I'm a bit hesitant about Chocolatey, as I'm not sure it's something we want to encourage our customers to deploy on their DCs.

But the message about package management support is noted! We'll certainly keep an eye on things in this space and see what we can do for upcoming releases!
