### ISSUE TITLE
Users cant change their password's only admin can on DC

### ISSUE THREAD

**Issue by miharix** [lithnet/ad-password-protection#89]
Hi,

I wanted to implement your great project in our domain.
But unfortunately I'm now in state where users cant change their password's only admin can on DC.

Configuration is 2 DC "Win Server 2019 standard" and "Each server accesses a single copy of the store via a file share"
In step 4 https://blog.lithnet.io/2019/01/lppad-1.html?m=1
I can use also password that is pwned
When using  Get-PasswordFilterResult it works correctly 

When trying to change user password on user computer I always get that it doesn't met policy .

Set GPO to "Disable password filter=true" no change

Uninstalled lithnet, reboot both DC no change

Reinstall, reboot on both DC no change, 

Uninstalled lithnet, reboot both DC no change

In Event Viewer under Lithnet... I see the Get-PasswordFilterResult events but not others.

Anny tips how can I fix ?

**Comment by ryannewington** [comment]
@miharix 

If LPP has been uninstalled, then it's Windows that is preventing this.

Do you have a minimum password age set? By default user's can only change their password once per day. Admins can still reset the password though.

Ryan

**Comment by miharix** [comment]
@ryannewington 

OMG what a stupid mistake :)) I didn't know that minimum password age exist.
https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/minimum-password-age

It works, and of course now also Lithnet works perfect :)
