### ISSUE TITLE
Import-CompromisedPasswordHashes Error Line #1 was not recognized

### ISSUE THREAD

**Issue by Dayst01** [lithnet/ad-password-protection#90]
If we want to import HIBP List v8 SHA-1 ordered by Hash we get these error from cmdlet:

Import-CompromisedPasswordHashes : Line #1 was not recognized as a hexadecimal hash. Lines must end with a new line
character or colon
The following line was invalid:
000000005AD76BD555C1D6D771DE417A4B87E4B4:10
In Zeile:1 Zeichen:1
+ Import-CompromisedPasswordHashes -Filename C:\Temp\pwned-passwords-sh ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-CompromisedPasswordHashes], InvalidDataException
    + FullyQualifiedErrorId : System.IO.InvalidDataException,Lithnet.ActiveDirectory.PasswordProtection.PowerShell.Imp
   ortCompromisedPasswordHashes

What can we do? Because the file is to big to open the check if the first line is really not correct.

**Comment by ryannewington** [comment]
You can't import the sha1 hash list. It must be the ntlm hash list.

**Comment by Dayst01** [comment]
Thanks Ryan next time I should read the lines in the guide properly :-)
