### ISSUE TITLE
Lithnet allowing all passwords

### ISSUE THREAD

**Issue by Late-Bleep** [lithnet/ad-password-protection#91]
We've recently installed Lithnet on our AD's (Windows Server 2022) and configured it to work with the HaveiBeenPwned store located on a DFS share.  

Using the Test-IsCompromisedPassword command on the DC returns expected results for something like Password123 however when we change a users password via AD or the Ctrl+Alt+Delete method the same password will be accepted. The event viewer displays event ID's 4 and 5 for said user so it appears that Lithnet is being triggered for password changes.

I've made our Microsoft Password Policy as simple as possible to avoid any conflicts during this testing period

I've also checked the Registry of the machine we're using to change the users password and the HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Lithnet\PasswordFilter\Default does have entries that are set to true

I've also tested changing my password to the account name of the user to see if it's an issue with the password store however this is also accepted.

Any help regarding this issue would be greatly appreciated.

![2022-12-05 12_21_14-m](https://user-images.githubusercontent.com/114970874/205529355-c5264d4a-ddd3-414a-ad34-2b2ea585af6b.png)

**Comment by ryannewington** [comment]
Hi @Late-Bleep 

What's the result of [Get-PasswordFilterResult](https://docs.lithnet.io/password-protection/advanced-help/powershell-reference/get-passwordfilterresult). This is calling the password filter the same way a password change would. Whereas Test-IscompromisedPassword is just telling you if that password is in the store or not.

FYI the GPO needs to apply to the DCs - it doesn't have any effect on the clients.

**Comment by Late-Bleep** [comment]
Ah! I wasn't applying the policy to the DC's, apologies for not following the documentation thoroughly. I've tested it now and everything appears to be working as expected.

Thanks for your quick and helpful response

**Comment by ryannewington** [comment]
No problems! Glad you got it working!
