### ISSUE TITLE
Passwords not being rejected when found in compromised password store

### ISSUE THREAD

**Issue by bezzoh** [lithnet/ad-password-protection#93]
I have set this up for one of my domains today and imported the latest hashed PW list from HIBP.

I have applied policies as per the 1st screenshot below. Complexity policies all work just fine, as does detection of userames, etc... but compromised passwords are being accepted.  PowerShell queries (Get-PasswordFilterResult) acknowledge that passwords I'm attempting are compromised, and even log to event viewer when doing so (see 2nd screenshot.) However if I reset such a password, either as a user on a PC or admin in ADUC, compromised passwords are accepted without complaint.

![Screenshot 2022-12-15 at 15 39 51](https://user-images.githubusercontent.com/63741935/207903382-c24262a4-9f0e-4228-8dc2-d3a0e3d02ab3.png)

![Screenshot 2022-12-15 at 15 41 55](https://user-images.githubusercontent.com/63741935/207904000-0dbb04ba-eab1-4567-b506-ef041e84fce4.png)

**Comment by ryannewington** [comment]
@bezzoh 

Are there any event log entries from the password filter?

My guess would be that the DC doesn't have permission to read the password store. If its stored locally to the DC, make sure `SYSTEM` has read access. If it's on a network share, make sure the `Domain Controllers` group has read permission to the share.

**Comment by bezzoh** [comment]
Nailed it! Thanks Ryan. The network share was on a DFS cluster and I had domain 'users' with read... not domain controllers. Awesome.
