### ISSUE TITLE
Prompt User on failed attempt at changing password?

### ISSUE THREAD

**Issue by Tracchy** [lithnet/ad-password-protection#96]
Hello,

We've been using lithnet with great success, but wanted to see if there was a way to present the user with a message when failing to change a password?  Would that be a setting we overlooked?  An example being, they reached X amounts of points out of "this many needed" or "this password matches one compromised"?

**Comment by ryannewington** [comment]
Hi @Tracchy 

Unfortunately, Windows only reports the very unhelpful "Your password does not meet the length, history, complexity requirements..." no matter what the cause of the policy violation. There isn't an API we can use that allows us to produce a more informative message for the end user.
